@startuml DCU_CampusEats
title Diagramme de Cas d'Utilisation — CampusEats

left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

' ===== ACTEURS =====
actor "Visiteur" as V
actor "Etudiant" as E
actor "Cuisinier" as C
actor "Livreur" as L
actor "Administrateur" as A

' Héritage
V <|-- E

' ===== CAS D'UTILISATION =====

rectangle "CampusEats — Système de Commande Cantine" {

  ' Fonctionnalité 1 : Authentification (Membre 1)
  usecase "S'inscrire" as UC1
  usecase "Se connecter" as UC2
  usecase "Se déconnecter" as UC3
  usecase "Recharger son solde" as UC4

  ' Fonctionnalité 2 : Menu (Membre 2)
  usecase "Consulter le menu" as UC5
  usecase "Ajouter un plat au menu" as UC6
  usecase "Supprimer un plat" as UC7
  usecase "Gérer les stocks" as UC8

  ' Fonctionnalité 3 : Commande (Membre 3)
  usecase "Passer une commande" as UC9
  usecase "Annuler une commande" as UC10
  usecase "Payer la commande" as UC11
  usecase "Consulter son historique" as UC12

  ' Fonctionnalité 4 : Livraison (Membre 4)
  usecase "Démarrer une livraison" as UC13
  usecase "Confirmer la remise" as UC14
  usecase "Signaler un échec" as UC15

  ' Fonctionnalité 5 : Admin (Membre 5)
  usecase "Voir le tableau de bord" as UC16
  usecase "Lister les étudiants" as UC17
  usecase "Voir les statistiques" as UC18
  usecase "Gérer les alertes" as UC19
}

' ===== RELATIONS ACTEURS =====
V --> UC1
V --> UC5
E --> UC2
E --> UC3
E --> UC4
E --> UC9
E --> UC10
E --> UC12

C --> UC6
C --> UC7
C --> UC8

L --> UC13
L --> UC14
L --> UC15

A --> UC16
A --> UC17
A --> UC18
A --> UC19

' ===== RELATIONS INCLUDE/EXTEND =====
UC9 ..> UC11 : <<include>>
UC9 ..> UC5  : <<include>>
UC6 ..> UC8  : <<include>>
UC10 ..> UC11 : <<extend>>
UC14 ..> UC13 : <<include>>
UC16 ..> UC18 : <<include>>
UC16 ..> UC19 : <<include>>

@enduml
