@startuml DS_CommandeRepas_Sprint1
title Diagramme de Séquence — Scénario Principal : Commander un repas (Sprint 1)

actor "Etudiant" as E
participant "Main" as M
participant "Etudiant" as ET
participant "Menu" as MN
participant "Commande" as C
participant "Livraison" as L

M -> ET : new Etudiant(id, nom, email, mdp, solde)
activate ET
M -> ET : seConnecter(email, mdp)
ET --> M : true (connexion réussie)
deactivate ET

M -> MN : new Menu(id, date, cuisinier)
activate MN
M -> MN : ajouterPlat(couscous)
M -> MN : ajouterPlat(jus)
M -> MN : afficherMenu()
MN --> M : liste des plats
deactivate MN

M -> C : new Commande(id, etudiant, heure)
activate C
M -> C : ajouterPlat(couscous)
M -> C : ajouterPlat(jus)

alt Paiement possible (solde suffisant)
  M -> C : passerCommande()
  activate C
  C -> ET : debiterSolde(total)
  ET --> C : true
  C --> M : Commande confirmée ✅
  deactivate C
else Solde insuffisant
  C --> M : ❌ Solde insuffisant
end

M -> L : new Livraison(id, commande, livreur, point)
activate L
M -> L : demarrerLivraison()
L --> M : Livraison démarrée
M -> L : confirmerLivraison(heure)
L --> M : Remise confirmée ✅
deactivate L

@enduml
